language: objective-c
osx_image: xcode7.1
script:
  xctool
  -workspace my\ note.xcworkspace
  -scheme my\ note
  -sdk iphonesimulator9.1
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
